ENCODED_ONE                       = "\001"
ENCODED_TEN                       = "\n"
ENCODED_42                        = "*"

ENCODED_UNDEFINED_MARKER          = "\000"
ENCODED_NULL_MARKER               = "\001"
ENCODED_FALSE_MARKER              = "\002"
ENCODED_TRUE_MARKER               = "\003"
ENCODED_INTEGER_MARKER            = "\004"
ENCODED_DOUBLE_MARKER             = "\005"
ENCODED_STRING_MARKER             = "\006"
ENCODED_XML_DOCUMENT_MARKER       = "\a"
ENCODED_DATE_MARKER               = "\b\001"
ENCODED_ARRAY_MARKER              = "\t"
ENCODED_OBJECT_MARKER             = "\n"
ENCODED_XML_MARKER                = "\v"
ENCODED_BYTE_ARRAY_MARKER         = "\f"

ENCODED_EMPTY_STRING              = ENCODED_NULL_MARKER
ENCODED_LOW_BIT_OF_ONE            = ENCODED_NULL_MARKER
ENCODED_DYNAMIC_OBJECT_MARKER     = ENCODED_XML_MARKER
ENCODED_ANONYMOUS_OBJECT_MARKER   = ENCODED_NULL_MARKER
ENCODED_CLOSE_OBJECT_MARKER       = ENCODED_NULL_MARKER

MAX_INTEGER                       = 268435455
MIN_INTEGER                       = -268435456
